// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:9ec1f07e-f8d3-48e9-bde6-3d89e2d2cf2e",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_b9wqTfig3",
    "aws_user_pools_web_client_id": "7d5ribpv25kcipsdk0as41hgsr",
    "aws_mobile_analytics_app_id": "b896c7cad80641bea1c61852488de248",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_content_delivery_bucket": "loative-20181211125851-hostingbucket",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "http://loative-20181211125851-hostingbucket.s3-website-eu-west-1.amazonaws.com"
};

export default awsmobile;
